---
output:
  html_document:
    fig_width: 5
    highlight: null
    keep_md: yes
---
```{r, message=FALSE, echo=FALSE, warning=FALSE}
options(warn=-1)
d <- readLines("README.md")
d <- gsub("\\.\\/README_files", "./readme/README_files", d)
writeLines(d, "../README.md")
rm(list=ls())
```

# Risk
A R package for make simpler the validation procedures of models.

## Installation
You can install `risk` from `github` using the `devtools` package.

```{r, message=FALSE}
if (!require("devtools"))
  install.packages("devtools")
devtools::install_github("jbkunst/risk")
```

## Valdation

This package assume: `1` for a good characteristic, `0` otherwise. 

```{r, message=FALSE, echo=FALSE}
library(risk)
```

```{r, message=FALSE}
data(predictions)
head(predictions)

score <- predictions$score*1000
label <- predictions$label

# Some indicators
ks(score, label)
aucroc(score, label)

# A lot of indicators
score_indicators(score, label)

# Odds Table
oddstable(score, label)
oddstable(score, label, breaks = 0:5*200)

# Confussion matrix
conf_matrix(ifelse(score<500, 0, 1), label)
```


## Ploting
```{r, message=FALSE}
plot_roc(score, label)
plot_gain(score, label)
```
